Delete (TREE, VAL)

Step 1: IF TREE = NULL
Write "VAL not found in the tree"
ELSE IF VAL < TREE -> DATA
Delete(TREE->LEFT, VAL)
ELSE IF VAL > TREE -> DATA
Delete(TREE -> RIGHT, VAL)
ELSE IF TREE -> LEFT AND TREE -> RIGHT
SET TEMP = findLargestNode(TREE -> LEFT)
SET TREE -> DATA = TEMP -> DATA
Delete(TREE -> LEFT, TEMP -> DATA)
ELSE
SET TEMP = TREE
IF TREE -> LEFT = NULL AND TREE -> RIGHT = NULL
SET TREE = NULL
ELSE IF TREE -> LEFT != NULL
SET TREE = TREE -> LEFT
ELSE
SET TREE = TREE -> RIGHT
[END OF IF]
FREE TEMP
[END OF IF]
Step 2: END